theme: jekyll-theme-candyman
logo: /J-Daniels-&-Associates.png
plugins:
  - jekyll-seo-tag
webmaster_verifications:
  google: K1kt4EgmD0wZIWG-HQ9hd_XAr5PVWkRsgsc0ZSkzinI
  bing: 5CCBB5DA4540EDB5CB6BBFB122A7912B
  alexa: 1234
  yandex: 1234
  baidu: 1234
